# Generated by Django 2.0.1 on 2018-01-05 20:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name_plural': 'People'},
        ),
        migrations.AlterField(
            model_name='organization',
            name='links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, help_text='External web links, comma-separated.', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='person',
            name='links',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, help_text='External web links, comma-separated.', null=True, size=None),
        ),
    ]
